### PR TITLE
Update criteo.md

### PR DESCRIPTION
**Pull request by casey-murray**
Need to omit (Beta) from the title as we have clients using the integration and it is no longer in Beta.

### CODE REVIEW

**Comment by vgiurgiu** [comment]
Hi @casey-murray , thanks for creating this PR. Before we can publish your update, please address the two comments below: 

1. The logo for the Criteo destination still shows your destination as beta (see screenshot below). Please share an updated logo with us at the same email address you used when submitting the destination documentation initially. Instructions are [here](https://experienceleague.adobe.com/docs/experience-platform/destinations/destination-sdk/guides/submit-destination.html?lang=en). 

Screen Shot 2023-01-03 at 10 37 14 AM

2. Please also remove the sentence `This is currently a beta product and functionality is subject to change.` from the note at the top of the Criteo destination page.

**Comment by vgiurgiu** [comment]
@casey-murray - checking in. Please see my latest comment and let me know if you have any questions. Thanks!

**Comment by casey-murray** [comment]
Hi @vgiurgiu - Apologies for missing the replies/notifications. Thanks for getting back to us. 

I've attached the logo below. Also, I removed the Beta phrasing from the documentation noted under "Files Changed"

Criteo-Logo-Sunrise

Please let me know if this is insufficient. 

Thanks!

**Comment by vgiurgiu** [comment]
@casey-murray - we'll be closing this stale pull request. I know that there was an email thread where the Criteo team was considering creating a destination submission for an updated destination based on a different API on your side, and then calling the destination GA (as opposed to the current beta designation).

When you are ready to make the update, please submit the new destination (instructions here: https://experienceleague.adobe.com/en/docs/experience-platform/destinations/destination-sdk/guides/submit-destination) and either reopen this pull request for the documentation update or open a new one.

Thanks very much,
Victor

**Pull request closed without merging**
