### PR TITLE
CJM-40987 Document AJO Web personalization use-case in Web SDK

### PR DESCRIPTION
**Pull request by XDex**
Document AJO Web personalization use-case in Web SDK, see https://jira.corp.adobe.com/browse/CJM-40987

Note: AJO Support in Web SDK will be available in alloy v2.14 (to be released soon)

### CODE REVIEW

**Comment by XDex** [comment]
@pnolan89 Please take a look when you get a chance, we'd appreciate having this PR merged before the upcoming Web SDK v2.14 release next Monday. Thank you!

**Comment by vfalon** [comment]
@XDex since this is related to Web SDK, it falls in my ballpark. @pnolan89 I think you only need to take a look at the extension page. I'll review the rest. Thanks!

**Comment by XDex** [comment]
Thanks @vfalon!

**Comment by jfkhoury** [comment]
Thank you @XDex ! My only comment is that we need a section names `What are surfaces` explaining the concept. We might need Pete's help here to really explain the vision behind them.

**Comment by vfalon** [comment]
PR was copied to internal repo and reviewed. Ready for publishing on release day. Closing this one.

**Pull request closed without merging**
